name: dependabot-targe-branch-update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  update:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install packages
      run: |
        sudo apt update
        sudo apt install -y jq
    - name: Git config
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
    - name: Update security/dependabot branch
      run: |
        LATEST_MAIN_COMMIT=$(gh api repos/${{ github.repository }}/branches/main --jq '.commit.sha')
        LATEST_SECURITY_COMMIT=$(gh api repos/${{ github.repository }}/branches/security/dependabot --jq '.commit.sha')

        if [ "$LATEST_MAIN_COMMIT" != "$LATEST_SECURITY_COMMIT" ]; then
          echo "Merging latest main branch into security/dependabot..."
          git fetch
          git checkout security/dependabot || git checkout -b security/dependabot
          git pull origin security/dependabot
          git merge origin/main
          if [ $? -eq 0 ]; then
            echo "Successfully merged main into security/dependabot"
            git push origin security/dependabot
          else
            echo "Failed to merge main into security/dependabot"
          fi
        else
          echo "security/dependabot is already up to date with main"
        fi
    - name: Create pr
      run: |
        pr=$(gh pr list --base "main" --head "security/dependabot" --state "open" --json number --jq '.[0].number')
        if [ -z "$pr" ]; then
          echo "Creating empty commit for dependabot target branch update..."
          git fetch
          git checkout security/dependabot || git checkout -b security/dependabot
          git commit --allow-empty -m "Empty commit for dependabot target branch update"
          git push origin security/dependabot
          if [ $? -eq 0 ]; then
            echo "Successfully created empty commit for dependabot target branch update"
          else
            echo "Failed to create empty commit for dependabot target branch update"
            exit 1
          fi

          echo "Creating pull request from security/dependabot to main..."
          gh pr create --base main --head security/dependabot --title "Merge security/dependabot into main" --body "Automatically created PR to merge security/dependabot into main with the latest changes."
          if [ $? -eq 0 ]; then
            echo "Successfully created pull request from security/dependabot to main"
          else
            echo "Failed to create pull request from security/dependabot to main"
            exit 1
          fi
        else
          echo "Pull request #$existing_pr already exists from security/dependabot to main"
        fi
    - name: Update target branch
      run: |
        prs=$(gh pr list --search "author:app/dependabot" --json number,baseRefName --jq '.[] | select(.baseRefName != "security/dependabot") | .number')

        for pr_number in $prs; do
          echo "Updating base branch for PR #$pr_number..."
          gh pr edit $pr_number --base "security/dependabot"
          if [ $? -eq 0 ]; then
            echo "Successfully updated target-branch PR #$pr_number"
          else
            echo "Failed to update target-branch PR #$pr_number"
          fi
        done
